CC = gcc
CFLAGS = -g -Wall -I.

default: test61

meeting: meeting.c
	$(CC) $(CFLAGS) -o meeting meeting.c

tsquare: tsquare.c
	$(CC) $(CFLAGS) -o tsquare tsquare.c

punctuation: punctuation.c
	$(CC) $(CFLAGS) -o punctuation punctuation.c

toyarmy: toyarmy.c
	$(CC) $(CFLAGS) -o toyarmy toyarmy.c

equiv: equiv.c
	$(CC) $(CFLAGS) -o equiv equiv.c

danger: danger.c
	$(CC) $(CFLAGS) -o danger danger.c

watermelon: watermelon.c
	$(CC) $(CFLAGS) -o watermelon watermelon.c

longword: longword.c
	$(CC) $(CFLAGS) -o longword longword.c

sale: sale.c
	$(CC) $(CFLAGS) -o sale sale.c

fastmath: fastmath.c
	$(CC) $(CFLAGS) -o fastmath fastmath.c

domino: domino.c
	$(CC) $(CFLAGS) -o domino domino.c

clean:
	rm -f *.o *~
